## Data Science
* Exploration - identifying patterns in information
* Prediction - using known info to make informed guesses
* Inference - quantifying degree of certainty

## Observational Studies
* Making conclusions based on **observed** data
* Measuring an outcome based on a treatment
* Association - relation between treatment and outcome

### Which of the following describes an observational study?
1. A study took random sample of adults and asked them about their bedtime habits. The data showed that people who drank a cup of tea before bedtime were more likely to go to sleep earlier than those who didn't drink tea.

2. Another study took a group of adults and randomly divided them into two groups. One group was told to drink tea every night for a week, while the other group was told not to drink tea that week. Researchers then compared when each group fell asleep.

Source: [Khan Academy](https://www.khanacademy.org/math/ap-statistics/gathering-data-ap/types-of-studies-experimental-vs-observational/a/observational-studies-and-experiments "Title")

### Which of the following describes an observational study?
1. A study randomly assigned volunteers to one of two groups:
    * One group was directed to use social media sites as they usually do.
    * One group was blocked from social media sites.<br/>The researchers looked at which group tended to be happier.
2. Another study took a random sample of people and examined their social media habits. Each person was classified as either a light, moderate, or heavy social media user. The researchers looked at which groups tended to be happier.

Source: [Khan Academy](https://www.khanacademy.org/math/ap-statistics/gathering-data-ap/types-of-studies-experimental-vs-observational/a/observational-studies-and-experiments "Title")

## Causality
* Find association
* Treatment group and control group should be comparable (use randomization)
* Confounding factors - underlying difference between the two groups, aside from treatment
* Difficult to make conclusions about causality with presence of confounding factors

### I want to conduct a study on whether eating breakfast the morning of an exam affects test performance.
* How do we make this a Random Controlled Experiment (what information would we need, who are the subjects, how do we divide the groups, etc.)?
* What are potential confounding factors?

## Data Types
* floats
* ints
* strings

In [2]:
# float and int variable declaration
interest_rate = 0.02
year = 2019

In [5]:
# dividing ints
my_num1 = 2 / 2
my_num1

1.0

In [8]:
# multiplying ints
my_num2 = 8 * 2
my_num2

16

In [14]:
# multiplying int and float
my_num3 = 7.8882392039840
round(my_num3, 2)

7.89

In [1]:
# string variable declaration
my_string = bye # will give error, need quotes around string literal
my_string

NameError: name 'bye' is not defined

In [2]:
# string arithmetic
first_name = 'John'
last_name = 'Smith'
full_name = first_name + " " + last_name
full_name

'John Smith'

In [3]:
print(full_name)

John Smith


In [4]:
# string conversion
my_name = 'Bob'
my_age = 100
my_string = "My name is " + my_name + " and I am " + str(my_age) + " years old."
my_string

'My name is Bob and I am 100 years old.'

In [5]:
print(32 + 64)

96


## Arrays

In [8]:
# array declaration
from datascience import *  
my_array = make_array(4, 5, 2, 1, 3)
my_array

array([4, 5, 2, 1, 3])

In [10]:
# Arrays are ordered. How do we access the 3rd element of my_array? What about the 6th?
# cannot access 6th, there are only 5 elements
my_array[2]

2

In [11]:
# how can we get the length of my_array?
len(my_array)

5

In [13]:
# other array operations
import numpy as np
sorted_my_array = np.sort(my_array)
sorted_my_array

array([1, 2, 3, 4, 5])

## Ranges

In [14]:
range1 = np.arange(27)
range1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [15]:
range2 = np.arange(4, 10)
range2

array([4, 5, 6, 7, 8, 9])

In [16]:
range3 = np.arange(50, 100, 5)
range3

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])